# Model arguments
model_name_or_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/ckpt/base_model/Qwen2.5-3B-Instruct
run_name: "STPO-math-Qwen2.5-3B-Instruct-4"
output_dir: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/ckpt/RLCR/STPO-math-Qwen2_5-3B-Instruct-4
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/huggingface/mehuldamani/big-math-digits
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# STPO script options (answer selection)
answer_selection_format_pattern: "ta"
answer_selection_strategy: "random"
answer_selection_balanced_correct_fraction: 0.5
answer_selection_reward_funcs:
- format_answer_segment
- accuracy
answer_selection_reward_weights: [0.1, 1.0]

# STPO trainer config
bf16: true
beta: 0.0
eval_strategy: "steps"
eval_steps: 50
eval_on_start: false
format_pattern: "tabc"
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: "end"
learning_rate: 5e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: linear
mask_truncated_completions: true
max_prompt_length: 1024
max_answer_length: 4096
max_confidence_length: 768
max_steps: -1
num_answer_candidates: 32
num_answer_selected: 8
num_iterations: 1
num_train_epochs: 1
overwrite_output_dir: true
per_device_eval_batch_size: 64
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- wandb
reward_funcs:
- format_confidence_segment
- accuracy
- brier
- mean_confidence
- confidence_one_or_zero
reward_weights: [0.5, 0.5, 0.5, 0.000001, 0.000001]
save_strategy: "steps"
save_steps: 60
save_total_limit: 10
save_only_model: true
scale_rewards: false
seed: 43
sys_prompt_name: "instruct_tabc"
temperature: 0.7
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
warmup_ratio: 0.20

# STPO-specific options
answer_stop_str: "</answer>"
confidence_stop_str: "</confidence>"
apply_answer_loss_on_first_confidence_only: true
